export const DATAS = {
    ALLO: 'Allo', CRITIQUES: 'Critiques',
    ACCUEIL: 'Accueil',
    WISHLIST: 'Mes films à voir',
    WATCHED: 'Mes films déjà-vu',
    LOG_REGISTER: 'Se connecter / S\'inscrire',
    ACCOUNT: 'Mon Compte',
    VALIDER: 'Valider',
    BTN_CONTACT: 'Un probleme ? Une erreur dans notre site ? Une remarque ?',
    BTN_CONTACT2: 'Pour toute question ou remarque, veuillez nous contacter sur Slack (Théo, Imen, Alan) ou par mail',
    FERMER: 'Fermer',
    COPYRIGHT: '© Copyright',
    CONTACT: 'Contact',
    CONNEXION: 'Connexion',
    INSCRIPTION: 'Inscription',
    INSCRIRE: 'S\'inscrire',
    MY_WISHLIST: 'Ma Wishlist',
    ADD_WISHLIST: 'Ajouter à la Wishlist ?',
    IN_WISHLIST: 'Dans la Wishlist',
    ONE_MOVIE_WISHLIST: ' film dans la Wishlist',
    MOVIES_WISHLIST: ' films dans la Wishlist',
    BAD_CRITICS: 'Commentaires Négatifs',
    GOOD_CRITICS: 'Commentaires Positifs',
    CRITICS: 'Lorem ipsum tas nec. Donec tempor libero eu metus molestie sagittis. Sed dignissim gravida orci. Curabitur luctus nulla metus, sed  blandit sem egestas nec. Donec tempor libero eu metus molestie sagittis.',
    SEARCH: 'Search',
    EMPTY: "Ajoutez des films à votre wishlist ! ;)",
    DELETE: "Supprimer",
}

export const MOVIES = {
    RELEASED: 'Date de sortie: ',
    RUNTIME: 'Durée: ',
    MIN: ' min',
    GENRE: 'Genre: ',
    DIRECTOR: 'Réalisateur: ',
    ACTORS: 'Acteurs: ',
    SYNOPSIS: 'Synopsis: '
}